### ISSUE TITLE
New maintainer for Samsung Galaxy 10 Series

### ISSUE THREAD

**Issue by Jubscleisson** [PixelOS-AOSP/official_devices#190]
## Name and Codename of the device you want to apply for 
```
Samsung Galaxy S10e (beyond0lte)
Samsung Galaxy S10 (beyond1lte)
Samsung Galaxy S10+ (beyond2lte)
Samsung Galaxy S10 5G (beyondx)
Samsung Galaxy Note10 (d1)
Samsung Galaxy Note10+ (d2s)
Samsung Galaxy Note10+ 5G (d2x)
```

## Device Tree sources

```
Device-specific Repository:
https://github.com/Jubscleisson/android_device_samsung_beyond0lte
https://github.com/Jubscleisson/android_vendor_samsung_beyond0lte

https://github.com/Jubscleisson/android_device_samsung_beyond1lte
https://github.com/Jubscleisson/android_vendor_samsung_beyond1lte

https://github.com/Jubscleisson/android_device_samsung_beyond2lte
https://github.com/Jubscleisson/android_vendor_samsung_beyond2lte

https://github.com/Jubscleisson/android_device_samsung_beyondx
https://github.com/Jubscleisson/android_vendor_samsung_beyondx

https://github.com/Jubscleisson/android_device_samsung_d1
https://github.com/Jubscleisson/android_vendor_samsung_d1

https://github.com/Jubscleisson/android_device_samsung_d2s
https://github.com/Jubscleisson/android_vendor_samsung_d2s

https://github.com/Jubscleisson/android_device_samsung_d2x
https://github.com/Jubscleisson/android_vendor_samsung_d2x

Common Repository:
https://github.com/Jubscleisson/android_device_samsung_exynos9820-common
https://github.com/Jubscleisson/android_vendor_samsung_exynos9820-common
https://github.com/Jubscleisson/android_device_samsung_slsi_sepolicy

Kernel Repository:
https://github.com/Jubscleisson/android_kernel_samsung_exynos9820
```

## What ROM's do you maintain officially/unofficially
```
crDroid (Officially)
PixelExtended (Officially)
PixelOS (Unofficially)
```

## How long have you been building Custom ROMs
```
1 year, I started builiding roms in January 2022
```

## Any Exceptions/special concern?
```
VoLTE/VoWiFi doesn't work
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@Jubscleisson
```

### Link to your XDA thread of unofficial build

```
S10 Series:
https://forum.xda-developers.com/t/rom-13-0-unofficial-pixelos-aosp-encryption-stable-04-02-2023.4506553/

Note10 Series:
https://forum.xda-developers.com/t/rom-13-0-unofficial-pixelos-aosp-encryption-stable-04-02-2023.4506557/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/exynos9820oss/105702
```

**Comment by bheatleyyy** [comment]
Thank you for your application, we're about to release the sources for the January update which has numerous changes. Apologies for the inconvenience, but would you mind rebuilding and releasing it then reapplying based on the newest sources? Thanks

**Comment by Jubscleisson** [comment]
> 

Oh, sure. I'll wait for the source release with the January SPL :)

**Comment by Jubscleisson** [comment]
Hi sir, I'm trying to build PixelOS with QPR1 but apparently the manifest hasn't been updated even though other repositories have been updated, what should I do in this case? 
![image](https://user-images.githubusercontent.com/88538132/215264976-45fd2918-456e-463a-aa80-40418fd8119f.png)

**Comment by bheatleyyy** [comment]
> Hi sir, I'm trying to build PixelOS with QPR1 but apparently the manifest hasn't been updated even though other repositories have been updated, what should I do in this case? ![image](https://user-images.githubusercontent.com/88538132/215264976-45fd2918-456e-463a-aa80-40418fd8119f.png)

Hello there, apologies for the delay. We have finished pushing our source and manifest. Feel free to build and reapply.

**Comment by Jubscleisson** [comment]
> Thank you for your application, we're about to release the sources for the January update which has numerous changes. Apologies for the inconvenience, but would you mind rebuilding and releasing it then reapplying based on the newest sources? Thanks

Builds and links updated, sir :)
