### ISSUE TITLE
No OTA for Sweet

### ISSUE THREAD

**Issue by lakshyarao22** [PixelOS-AOSP/official_devices#205]
I am unable to see OTA updater in system settings. How do I update the rom?
Build Number: TQ1A.230105.001.A2 PixelOS_sweet-13.0-20230202-0453

**Comment by Jubscleisson** [comment]
@lakshyarao22 lmafo

**Comment by Jubscleisson** [comment]
@Jubscleisson dumb bot

**Comment by basamaryan** [comment]
OTA is not present. Installation instructions are available on the website.

**Comment by lakshyarao22** [comment]
I am unable to update using dirty method. Kindly suggest what should I do.

**Comment by basamaryan** [comment]
Read the instructions. Dirty flashing works fine.

**Comment by lakshyarao22** [comment]
One last help! Can you confirm the steps as I previously dirty flashed the rom using orangefox recovery and ended up formatting my phone.

1. Reboot to recovery
2. Clear dalvik
3. Clear cache
4. Install the rom
5. Reboot to system

Thank you in advance.

**Comment by lakshyarao22** [comment]
And also is there any future plans to add OTA support as reflashing the rom is a little inconvenient and a little bit risky as well.

**Comment by basamaryan** [comment]
@lakshyarao22 As I said, please refer to the website for instructions. When a clean flash is needed, it is mentioned in the blog or the device changelog, I would refer to both of them. All OTA does is reflash the ROM. It's the same thing, just with having you download it manually, i.e. the "risk" factor stays the same
