### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by nnippon99** [PixelOS-AOSP/official_devices#208]
## Name and Codename of the device you want to apply for 
```
Redmi Note 11 Pro / Pro+ 5G (veux/peux)
```

## Device Tree sources

```
https://github.com/nnippon99/device_xiaomi_veux
https://github.com/nnippon99/vendor_xiaomi_veux
https://github.com/nnippon99/kernel_xiaomi_sm6375
https://github.com/nnippon99/device_xiaomi_veux-kernel
```

## What ROM's do you maintain officially/unofficially
```
None 
```

## How long have you been building Custom ROMs
```
Since 2016 breh
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
https://t.me/nnippon
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/PocoX4ProUpdates/161
```

**Comment by kardebayan** [comment]
@nnippon99 nipple gsi

**Comment by basamaryan** [comment]
Hi Nippon, 

As you could probably have guessed from the relative inactivity of the project, things have been very busy so it's taken a while to get around to your application, apologies for that.

While taking a look at your tree, I noticed the following issues:

- https://github.com/nnippon99/device_xiaomi_veux/commit/e1dae8a27f6b01caf7d0e3f7e8aeab0aab5d2066

**Comment by basamaryan** [comment]
Hi Nippon,  
 
As you could probably have guessed from the relative inactivity of the project, things have been very busy so it's taken a while to get around to your application, apologies for that. 
 
While taking a look at your tree, I noticed the following issues: 

- https://github.com/nnippon99/device_xiaomi_veux/commit/e1dae8a27f6b01caf7d0e3f7e8aeab0aab5d2066
No, it is not for some reason. You will need to inherit common_full_phone.

- https://github.com/nnippon99/device_xiaomi_veux/commit/b70ddf34d3aa2cb033b251f99d09a0048d06ea6f 
Is unnecessary as we have it in vendor_aosp.

- https://github.com/nnippon99/device_xiaomi_veux/commit/80dfae79937676385f933d531ee5d2b8900e21d6 
We do not have that overlay. We have a toggle for enabling/disabling it.

- https://github.com/nnippon99/device_xiaomi_veux/commit/030c1bf64caf8f8c088155976e8dd35c48d6406f
Your conflict resolution should not be in a different commit unrelated to what the commit message describes

- https://github.com/nnippon99/device_xiaomi_veux/commit/d16dcf83bb5d4b953bd4c64999162f88171a9622
This commit lacks a proper commit message, ideally, you would want to mention where you updated it from.

- https://github.com/nnippon99/device_xiaomi_veux/blob/thirteen/vendorsetup.sh and https://github.com/nnippon99/device_xiaomi_veux/tree/thirteen/GoogleCameraGo should not be in the tree

Thank you for your patience. Please let me know if you have any questions about the feedback I provided. I look forward to receiving your updated application.

**Comment by nnippon99** [comment]
Hey @basamaryan, thanks for your responce!
Regarding mentioned issues, I have resolved them and rebased the tree again.
Thanks for the support and revision of the current trees (was mess af).
I'm waiting for new responce.
Thanks again!.

**Comment by basamaryan** [comment]
@nnippon99 Hey, looks good to me apart from

- https://github.com/nnippon99/device_xiaomi_veux/commit/160930bd890ed3520272d71e7cc177336c76ef03 

I would drop that. We have https://github.com/PixelOS-AOSP/vendor_aosp/commit/01a55fce5f08f61547e9c13b1c15e3fbb71134b2

- https://github.com/nnippon99/device_xiaomi_veux/commit/70dd087f72909298b1bee3e3dc280acdb59fffd3 is not neccessary when you have https://github.com/nnippon99/device_xiaomi_veux/commit/299255eefc35dba3dae704b5af131ec54e0b6e96

**Comment by nnippon99** [comment]
Hey @basamaryan, again thanks for your responce.
Okay I have resolved these issues, you can check my trees again.
Tell me if I have something else to do, thanks sar.
