### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Chuck439** [PixelOS-AOSP/official_devices#213]
## Name and Codename of the device you want to apply for 
```
Redmi 8/8A/8A Dual/8A Pro/7A (Mi439)
```

## Device Tree sources

```
https://github.com/Mi-Thorium/android_device_xiaomi_Mi439/tree/a13/master
https://github.com/ChuckProjekt/device_xiaomi_mithorium-common
https://github.com/ChuckProjekt/vendor_xiaomi_mithorium-common
https://github.com/LineageOS/android_kernel_xiaomi_sdm439
```

## What ROM's do you maintain officially/unofficially
```
Official nusantara project
```

## How long have you been building Custom ROMs
```
2 year
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
https://github.com/begonia-dev/android_frameworks_base/commit/2dd4ceaae6f0e21acc608bb9752b1ffe41d1217c
https://github.com/begonia-dev/android_packages_apps_Settings/commit/a88066cb1451edb42e75eb66d3b6b8a3dbcba9a6
```

### Telegram username
```
https://t.me/mikaziku
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/ChuckXD/391
```

**Comment by bheatleyyy** [comment]
@Chuck439 Hello there, https://github.com/Mi-Thorium/android_device_xiaomi_Mi439/tree/a13/master the tree you linked here doesn't seem to have PixelOS bringup commit. Please link the tree you used to build the rom.

**Comment by Chuck439** [comment]
> @Chuck439 Hello there, https://github.com/Mi-Thorium/android_device_xiaomi_Mi439/tree/a13/master the tree you linked here doesn't seem to have PixelOS bringup commit. Please link the tree you used to build the rom.

Here is my tree used for pos
https://github.com/ChuckProjekt/device_xiaomi_Mi439/tree/pos-13

**Comment by bheatleyyy** [comment]
@Chuck439 Hello there, sorry for the delay. Everything looks good and we're welcoming you into the team with a warm heart. Pm me on https://t.me/Megalodonzs for further details.
