### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by dam0nsalva** [PixelOS-AOSP/official_devices#214]
## Name and Codename of the device you want to apply for 
```redmi k50i (xaga) 
Your device name (Your device codename)
```
Redmi k50i 
## Device Tree sources

```
https://github.com/wbs306/device_xiaomi_xaga
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/xaga-s-oss

```

## What ROM's do you maintain officially/unofficially
```
Insert here
```no one

## How long have you been building Custom ROMs
`
Insert here
```iam gonna try with pixel os

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

## Contact

### Telegram username
```dam0nsalva
Your Telegram username
```dam0nsalva

### Link to your XDA thread of unofficial build
<!-- Before being able to maintainer PixelOS officially, 
you must have already made an XDA 
Refer Maintainer Requirements -->
```
Link to where you have posted your build publically.
```

### Link to your unofficial PixelOS Build Post other than XDA
<!-- Before being able to maintainer PixelOS officially, 
you must have already made your unofficial build public. 
Refer Maintainer Requirements -->
```
Link to where you have posted your build publically.
```

**Comment by bheatleyyy** [comment]
@dam0nsalva Hello there, you have not filled out the form properly, make sure you keep in mind proper formatting if you apply again in future. The tree you linked doesn't have a proper bringup for our rom and does not look like it belongs to you.

Closing it as it does not follow proper formatting and does not fulfill the requirements.
