### ISSUE TITLE
New maintainer 

### ISSUE THREAD

**Issue by HELLINFIX** [PixelOS-AOSP/official_devices#216]
## Name and Codename of the device you want to apply for 
```
Realme Narzo 50/8i (spaced)
```

## Device Tree sources

```
Device-tree Repository:
https://github.com/realme-mt6781-dev/device_realme_spaced
Vendor-tree Repository:
https://github.com/realme-mt6781-dev/android_vendor_realme
Kernel-tree Repository:
https://github.com/realme-mt6781-dev/realme_kernel_mt6781
```

## What ROM's do you maintain officially/unofficially
```
Official:- AncientOS
Unofficial:- PixelOS,Ricedroid,LineageOS
```

## How long have you been building Custom ROMs
```
1 year 
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@HELLINFIX
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-13-0-official-pixelos-for-realme-8i-narzo-50-spaced-unofficial.4577605/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/Realme8iUpdates & https://sourceforge.net/projects/hellroms/
```

**Comment by bheatleyyy** [comment]
@HELLINFIX Hello there, Sorry for the delay. Everything looks good and we're welcoming you into the team with a warm heart. Pm me on https://t.me/Megalodonzs for further details.
