### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by cyberdroid1111** [PixelOS-AOSP/official_devices#229]
## Name and Codename of the device you want to apply for 
```
Realme GT Master (Lunaa/RMX3360/RMX3363/RMX3363)
```

## Device Tree sources

```
https://github.com/cyberdroid1111/android_device_realme_lunaa
https://github.com/cyberdroid1111/android_device_oneplus_sm8350-common
https://github.com/cyberdroid1111/android_kernel_oneplus_sm8350
https://github.com/cyberdroid1111/proprietary_vendor_realme_lunaa
https://github.com/cyberdroid1111/proprietary_vendor_oneplus_sm8350-common

```

## What ROM's do you maintain officially/unofficially
```
PixelOS, PixelExperience.
```

## How long have you been building Custom ROMs
```
2 years
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@cyberdroid23
```

### Link to your XDA thread of unofficial build

```
I will post builds in XDA soon
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/RealmeGTMasterUpdates/224
```

**Comment by basamaryan** [comment]
Invalid application. You can take a look at the device and maintainer requirements from https://blog.pixelos.net/docs/JoinTheTeam
