### ISSUE TITLE
Anisur Rahman

### ISSUE THREAD

**Issue by anischotora** [PixelOS-AOSP/official_devices#231]
## Name and Codename of the device you want to apply for 
```
Redmi K30 5G (picasso)
```

## Device Tree sources

```
https://github.com/anischotora/device_xiaomi_picasso.git
https://github.com/anischotora/kernel_xiaomi_picasso.git
https://gitlab.com/alosrobot/vendor_xiaomi_picasso.git
```

## What ROM's do you maintain officially/unofficially
```
risingos, cherishos officially , pixel experience plus a13 , project Elixir etc 
```

## How long have you been building Custom ROMs
```
1 year
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
alosrobot
```

### Link to your XDA thread of unofficial build

```
Link to where you have posted your build publically.
```
Telegram Group link =>> https://t.me/alosrobotS

### Link to your unofficial PixelOS Build Post other than XDA

```
Link to where you have posted your build publically.
```
https://forum.xda-developers.com/t/rom-13-unofficial-pixelos-picasso-stable-19-05-2023.4588775/

**Comment by whyredfire** [comment]
Hi, while reviewing your trees/ GitHub account we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
