### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by acex69** [PixelOS-AOSP/official_devices#234]
## Name and Codename of the device you want to apply for 
```
Redmi 9 (lancelot)
```

## Device Tree sources

```
https://github.com/ProjectElixir-Devices/device_xiaomi_lancelot
https://github.com/ProjectElixir-Devices/device_xiaomi_mt6768-common
https://github.com/acex69/kernel_xiaomi_mt6768
https://github.com/ProjectElixir-Devices/proprietary_vendor_xiaomi_lancelot
https://github.com/ProjectElixir-Devices/proprietary_vendor_xiaomi_mt6768-common
```

## What ROM's do you maintain officially/unofficially
```
Project Elixir (official) 
```

## How long have you been building Custom ROMs
```
2 years approx
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@acex88
```

### Link to your XDA thread of unofficial build

```
Made private build so no posts regarding it
```

### Link to your unofficial PixelOS Build Post other than XDA

```
Made private build so no posts regarding it
```

**Comment by whyredfire** [comment]
Hi, while reviewing your trees/ GitHub account we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.

**Comment by acex69** [comment]
> Hi, while reviewing your trees/ GitHub account we couldn't see much of what we would consider a reasonable experience/knowledge.
> You can apply again in the future whenever you've gained more experience.

Hi @whyredfire 
Thanks for replying and wasting your precious time on me 
I resently in January , my got account got hacked somehow and it was deleted
I don't know how it happened but my elixir team knows about it and that's why I am maintaining my device there .

Thanks

**Comment by whyredfire** [comment]
Have you read the device requirements properly for getting official?
Also, it is required to release a build publicly before you proceed with official status process.

I'm reopening this application and putting it on hold for the next two weeks.

**Comment by acex69** [comment]
> Have you read the device requirements properly for getting official?
> Also, it is required to release a build publicly before you proceed with official status process.
> 
> I'm reopening this application and putting it on hold for the next two weeks.

Yes I have build and it's stable enough to be proceed as official status

**Comment by acex69** [comment]
@whyredfire are you busy ?
If yes i may close close this and apply anytime in future

**Comment by acex69** [comment]
> > @whyredfire are you busy ? If yes i may close close this and apply anytime in future
> 
> Hi, I want you to release this build publicly and post it on XDA.
> 
> Meanwhile, you can also revert [ProjectElixir-Devices/device_xiaomi_mt6768-common@8ab98a1](https://github.com/ProjectElixir-Devices/device_xiaomi_mt6768-common/commit/8ab98a1a4987221ee586c73893d5c65cbf4ea066) and [ProjectElixir-Devices/device_xiaomi_mt6768-common@952eaa8](https://github.com/ProjectElixir-Devices/device_xiaomi_mt6768-common/commit/952eaa85bee4955f2bc11ffcd982233a56c7dd0d) as we don't allow removing packages as mentioned https://blog.pixelos.net/docs/JoinTheTeam/DeviceRequirements#:~:text=RemovePackages%20MUST%20NOT%20be%20used.%20This%20is%20a%20form%20of%20modifying%20the%20source%20code%2C%20and%20is%20not%20allowed.

HI @whyredfire 
As per your wish i have rebased the trees.
https://github.com/acex69/mt6768-common_fantastic
And can i please have the XDA Template ?

**Comment by whyredfire** [comment]
> > > @whyredfire are you busy ? If yes i may close close this and apply anytime in future
> > 
> > 
> > Hi, I want you to release this build publicly and post it on XDA.
> > Meanwhile, you can also revert [ProjectElixir-Devices/device_xiaomi_mt6768-common@8ab98a1](https://github.com/ProjectElixir-Devices/device_xiaomi_mt6768-common/commit/8ab98a1a4987221ee586c73893d5c65cbf4ea066) and [ProjectElixir-Devices/device_xiaomi_mt6768-common@952eaa8](https://github.com/ProjectElixir-Devices/device_xiaomi_mt6768-common/commit/952eaa85bee4955f2bc11ffcd982233a56c7dd0d) as we don't allow removing packages as mentioned https://blog.pixelos.net/docs/JoinTheTeam/DeviceRequirements#:~:text=RemovePackages%20MUST%20NOT%20be%20used.%20This%20is%20a%20form%20of%20modifying%20the%20source%20code%2C%20and%20is%20not%20allowed.
> 
> HI @whyredfire As per your wish i have rebased the trees. https://github.com/acex69/mt6768-common_fantastic And can i please have the XDA Template ?

https://github.com/PixelOS-AOSP/official_devices/blob/thirteen/docs/XDA_template.txt

**Comment by acex69** [comment]
> > > > @whyredfire are you busy ? If yes i may close close this and apply anytime in future
> > > 
> > > 
> > > Hi, I want you to release this build publicly and post it on XDA.
> > > Meanwhile, you can also revert [ProjectElixir-Devices/device_xiaomi_mt6768-common@8ab98a1](https://github.com/ProjectElixir-Devices/device_xiaomi_mt6768-common/commit/8ab98a1a4987221ee586c73893d5c65cbf4ea066) and [ProjectElixir-Devices/device_xiaomi_mt6768-common@952eaa8](https://github.com/ProjectElixir-Devices/device_xiaomi_mt6768-common/commit/952eaa85bee4955f2bc11ffcd982233a56c7dd0d) as we don't allow removing packages as mentioned https://blog.pixelos.net/docs/JoinTheTeam/DeviceRequirements#:~:text=RemovePackages%20MUST%20NOT%20be%20used.%20This%20is%20a%20form%20of%20modifying%20the%20source%20code%2C%20and%20is%20not%20allowed.
> > 
> > 
> > HI @whyredfire As per your wish i have rebased the trees. https://github.com/acex69/mt6768-common_fantastic And can i please have the XDA Template ?
> 
> https://github.com/PixelOS-AOSP/official_devices/blob/thirteen/docs/XDA_template.txt

Hi @whyredfire 
I have posted my rom on XDA as your request
https://forum.xda-developers.com/t/rom-13-unofficial-pixelos-aosp-stable-20-06-2023.4597891/

**Comment by Twel12** [comment]
Do You mind having some patience?, stop tagging whyredfire after every 2 mins. He will reply when its appropriate.

**Comment by acex69** [comment]
> Do You mind having some patience?, stop tagging whyredfire after every 2 mins. He will reply when its appropriate.
Sorry

**Comment by bheatleyyy** [comment]
Looks good, you can PM me on https://t.me/Megalodonzs for further details.
