### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RE800T** [PixelOS-AOSP/official_devices#235]
## Name and Codename of the device you want to apply for 
```
Google Pixel 6A (bluejay)
```

## Device Tree sources

```
• https://github.com/BluejayROM/android_device_google_gs-common
• https://github.com/BluejayROM/android_device_google_gs101
• https://github.com/BluejayROM/android_device_google_bluejay
```

## What ROM's do you maintain officially/unofficially
```
PixelOS
```

## How long have you been building Custom ROMs
```
Two years
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
https://t.me/Sezam4ik
```

### Link to your XDA thread of unofficial build

```
Not published
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/RALegacy_Bluejay/59
```

**Comment by bheatleyyy** [comment]
Looks good, you can PM me on https://t.me/Megalodonzs for further details.
