### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ahmedtohamy1** [PixelOS-AOSP/official_devices#238]
## Name and Codename of the device you want to apply for 
```
Mi 10T (Apollo)
```

## Device Tree sources

```
https://github.com/Apollo-Trees/vendor_xiaomi_sm8250-common/
https://github.com/Apollo-Trees/device_xiaomi_apollo
https://github.com/Apollo-Trees/device_xiaomi_sm8250-common
https://github.com/Apollo-Trees/vendor_xiaomi_apollo
```

## What ROM's do you maintain officially/unofficially
```
Evolution X (Official)
```

## How long have you been building Custom ROMs
```
4y
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
ahmed_tohamy
```

### Link to your XDA thread of unofficial build

```
Not published
```

### Link to your unofficial PixelOS Build Post other than XDA

```
(https://sourceforge.net/projects/ahmedtohamy-builds/files/PixelOS_apollo-13.0-20230621-1525.zip/download)
and tg device groups 
```

**Comment by whyredfire** [comment]
Hi there, 

As much as we would love to take you on as part of the team, as your skill speaks for itself, we don't believe you would fit the team dynamic so at this time we have to unfortunately say no at this time.
