### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by GTCxprice** [PixelOS-AOSP/official_devices#245]
## Name and Codename of the device you want to apply for 
```
Mi Mix 2 (Chiron)
```

## Device Tree sources

```
https://github.com/GTCxprice/android_device_xiaomi_chiron/tree/PixelOS
https://github.com/GTCxprice/android_device_xiaomi_msm8998-common.git
https://github.com/GTCxprice/android_kernel_xiaomi_msm8998.git
https://github.com/GTCxprice/proprietary_vendor_xiaomi_chiron.git
https://github.com/GTCxprice/proprietary_vendor_xiaomi_msm8998-common.git

```

## What ROM's do you maintain officially/unofficially
```
Project Kasumi (long time ago)
Pixel OS 
Derpfest
AlphaDroid
PixelExtended
Miku Ui
```

## How long have you been building Custom ROMs
```
Its been 2 years now 
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
GTCxprice (https://t.me/GTCxprice)
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-13-chiron-unofficial-pixel-os-aosp-19-feb-2023.4558723/#post-88751771
https://forum.xda-developers.com/t/rom-13-chiron-unofficial-pixel-os-aosp-stable-14-jul-2023.4605661/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/xiaomimimix2rom/292
https://t.me/xiaomimimix2rom/523
https://t.me/xiaomimimix2rom/587
https://t.me/xiaomimimix2rom/627
```

**Comment by whyredfire** [comment]
Hi, while reviewing your trees/ GitHub account we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
