### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Amritorock** [PixelOS-AOSP/official_devices#246]
## Name and Codename of the device you want to apply for 
```
Realme 5 series (r5x)
```

## Device Tree sources

```
https://github.com/Amritorock/device_realme_r5x
https://github.com/Amritorock/kernel_realme_r5x
https://github.com/Amritorock/vendor_realme_r5x
```

## What ROM's do you maintain officially/unofficially
```
Project Elixir (official) 
AlphaDroid (official)
PixelOS (Unofficial)
```

## How long have you been building Custom ROMs
```
Approx 2 years
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
Yes need some Commits to fix camera freezing 

https://github.com/PixelExperience/bionic/commit/e8ddba39b279533cfbceec60a1fe11f8bf45b9d3
https://github.com/PixelExperience/bionic/commit/8f0e4636bf7ce636507feb273b950158fe6ae11a
https://github.com/PixelExperience/bionic/commit/248e716d3f2e7e6cf548e13603f6bd85ac0dd613
```

### Telegram username
```
@Amritorock
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-r5x-dynamic-13-unofficial-pixelos-aosp-stable-19-07-2023.4607341/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/Realme5Dev/734512
```

**Comment by whyredfire** [comment]
Hello, Amrito! Here's our review.

- You don't need to build this package, https://github.com/Amritorock/device_realme_r5x/blob/473422ac572fa56e18b9e9360cb44a3de0db364a/device.mk#L60

- We already have these optimizations in our source vendor, https://github.com/Amritorock/device_realme_r5x/blob/473422ac572fa56e18b9e9360cb44a3de0db364a/device.mk#L156

- As mentioned in the rules, we donot allow RemovePackages, https://github.com/Amritorock/device_realme_r5x/blob/473422ac572fa56e18b9e9360cb44a3de0db364a/device.mk#L403

- We don't have lineage trust hal, https://github.com/Amritorock/device_realme_r5x/blob/473422ac572fa56e18b9e9360cb44a3de0db364a/device.mk#L474

- This flag isn't required, https://github.com/Amritorock/device_realme_r5x/blob/pos/aosp_r5x.mk#L30

- You should set this property to true, https://github.com/Amritorock/device_realme_r5x/blob/473422ac572fa56e18b9e9360cb44a3de0db364a/configs/props/product.prop#L36

- You can remove this, https://github.com/Amritorock/device_realme_r5x/blob/473422ac572fa56e18b9e9360cb44a3de0db364a/configs/props/system.prop#L96

- This is used for boost framework, AOSP ROMs like PixelOS don't have it, https://github.com/Amritorock/device_realme_r5x/blob/473422ac572fa56e18b9e9360cb44a3de0db364a/configs/props/vendor.prop#L201

- Consider removing these props, it should improve hwui perf https://github.com/Amritorock/device_realme_r5x/blob/473422ac572fa56e18b9e9360cb44a3de0db364a/configs/props/vendor.prop#L236-L242

Apart from this, consider cleaning your device tree and commit history in general and consider reapplying later.
