### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by cyberdroid1111** [PixelOS-AOSP/official_devices#250]
## Name and Codename of the device you want to apply for 
```
Device: RMX3360/61/63
Codename: Lunaa
```

## Device Tree sources

```
https://gitlab.com/CyberDroid23/android_device_realme_lunaa
https://gitlab.com/CyberDroid23/android_device_oneplus_sm8350-common
https://gitlab.com/CyberDroid23/proprietary_vendor_realme_camera
https://gitlab.com/CyberDroid23/vendor_oneplus_sm8350-common
https://gitlab.com/CyberDroid23/proprietary_vendor_realme_lunaa
https://gitlab.com/CyberDroid23/android_kernel_oneplus_sm8350
```

## What ROM's do you maintain officially/unofficially
```
PixelOS, PixelExperience, Corvus
```

## How long have you been building Custom ROMs
```
1.5 years
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@CyberDroid23
```

### Link to your XDA thread of unofficial build

```
Sorry, I didnt pushed any builds on XDA yet, But i'll do it next time. 😊
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/RealmeGTMasterUpdates/245
```

**Comment by bheatleyyy** [comment]
@cyberdroid1111 Hi, thank you for your application and interest in joining the PixelOS team.

We unfortunately cannot offer you a position at this time as we don't believe you would be a good fit for the team and there may be some clashing personalities. In addition, we couldn't find any contributions on your GitHub is something we look for in particular for maintainers.

Best of luck in your future endeavours,
The PixelOS team
