### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ImSurajx** [PixelOS-AOSP/official_devices#252]
## Name and Codename of the device you want to apply for 
```
Redmi Note 7 & 7S (lavender)
```

## Device Tree sources

```
https://github.com/Stable-Stuffs/android_device_xiaomi_lavender-p
https://github.com/Stable-Stuffs/android_kernel_xiaomi_lavender-p
https://github.com/Stable-Stuffs/android_vendor_xiaomi_lavender-p
```

## What ROM's do you maintain officially/unofficially
```
PixelExperience Stable Edition Unoffcially From 1.5 Years
ArrowOS Stable Editon & Many More
```

## How long have you been building Custom ROMs
```
2 Years
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
Only Default Camera Was Changed
Source: https://gitlab.com/ImSurajxD/packages_apps_android
```

### Telegram username
```
ItSurajx
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-unofficial-13-lavender-pixelos-aosp.4613857/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/RedmiNote7Updates
https://t.me/redminote7update
```

**Comment by whyredfire** [comment]
Hi, while reviewing your trees/ GitHub account we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
