### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Noah113-Allen** [PixelOS-AOSP/official_devices#254]
## Name and Codename of the device you want to apply for 
```
Redmi Note 10 5G/Poco M3 Pro 5G (camellia/camellian)
```

## Device Tree sources

```
https://github.com/Noah113-Allen/device_xiaomi_camellia
https://github.com/Noah113-Allen/device_xiaomi_camellia-kernel
https://github.com/Noah113-Allen/vendor_xiaomi_camellia
```

## What ROM's do you maintain officially/unofficially
```
PixelOS unofficial/LineageOS unofficial/ArrowOs unofficial
```

## How long have you been building Custom ROMs
```
almost 1 year
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
noah_allen
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-13-0-aosp-pixelos-13-0-unofficial-for-camellia-camellian-stable-20230718.4614455/
```
### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/pecamelliaupdates
```

**Comment by Noah113-Allen** [comment]
> Hi, why were these (https://github.com/Noah113-Allen/device_xiaomi_camellia/commits/6fea45083cea4a7694529e0a29d58b4bac2028d7) repicked from here (https://github.com/dm700-devs/device_xiaomi_camellia/commits/7bc062b22f1208e87b798921b056f1c16f452ce2).

Hello, I think I have already solved the issues you mentioned earlier. Could you please check again?

**Comment by whyredfire** [comment]
@Noah113-Allen +

**Comment by whyredfire** [comment]
Closing this issue based on the conversation we had on telegram.
