### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by INCENDIOCODM** [PixelOS-AOSP/official_devices#261]
## Name and Codename of the device you want to apply for 
``` Mi 11X Pro
Your device name (Your device codename): 
haydn

## Device Tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```

1. DT: 

https://github.com/INCENDIOCODM/android_device_xiaomi_haydn/tree/PixelOS-13

2. Common DT:

https://github.com/INCENDIOCODM/android_device_xiaomi_sm8350-common/tree/PixelOS-13

3.  Kernel:

https://github.com/INCENDIOCODM/android_kernel_xiaomi_sm8350

4.  Vendor:

https://github.com/INCENDIOCODM/proprietary_vendor_xiaomi_haydn

5. Common Vendor

https://github.com/INCENDIOCODM/proprietary_vendor_xiaomi_sm8350-common

## What ROM's do you maintain officially/unofficially
Crdroid and DroidX-UI (Both official)
```

## How long have you been building Custom ROMs
```
1 year + (approximately)  
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

## Contact

### Telegram name: Vinayak
Your Telegram username: @INNUENDOCODM

### Link to your XDA thread of unofficial build
<!-- Before being able to maintainer PixelOS officially, 
you must have already made an XDA 
Refer Maintainer Requirements -->
```
Link to where you have posted your build publically.

https://forum.xda-developers.com/t/rom-13-unofficial-pixelos-for-haydn-haydnin.4618499/

### Link to your unofficial PixelOS Build Post other than XDA

```
Link to where you have posted your build publically.
```

**Comment by cyberknight777** [comment]
Hi and thanks for applying, however at this time we can't accept you into the team unfortunately

Some issues we noticed are mainly to do with your kernel, namely:

We don't allow shipping KernelSU or pre-rooted builds for any form.

Commenting out loggers is bad practice, it's better to denote them to pr_debug() as seen here
https://github.com/INCENDIOCODM/android_kernel_xiaomi_sm8350/commit/2a214beeb655feacffb613f477d7a35f36ea5fd7

Finally, this commit is ill advised as calls can be made through Telegram and it doesn't effect all clients
https://github.com/INCENDIOCODM/android_kernel_xiaomi_sm8350/commit/7a85b61dde768091d588cfb61778dfccad4c0dde

Best of luck in any future endeavours

**Comment by INCENDIOCODM** [comment]
Thanks you for the kind reply :)

Our community dev have added everything that is kernel based 
And I don't want to touch it as I know I can mess kernel stuff
And about the kernel SU 
As you know it's kernel based 
And rom is not pre rooted even if you use kernel su 
It only gives access of root to selected apps that we have to choose individually

You guys know better than me, I hope you understand
And please allow to ship with kernel su, I use it for dtsx
