### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Ad1tyaS1ngh** [PixelOS-AOSP/official_devices#272]
## Name and Codename of the device you want to apply for 
```
Sony Xperia  5 II (pdx206)
```

## Device Tree sources

```
https://github.com/Ad1tyaS1ngh/device_sony_pdx206
https://github.com/Ad1tyaS1ngh/vendor_sony_pdx206
https://github.com/Ad1tyaS1ngh/kernel_sony_sm8250
```

## What ROM's do you maintain officially/unofficially
```
Project-Awaken
```

## How long have you been building Custom ROMs
```
3-4 years
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
Ad1tyaS1ngh
```

**Comment by Twel12** [comment]
achaaa

**Comment by Ad1tyaS1ngh** [comment]
> achaaa

Hi twel bhai

**Comment by sarthakroy2002** [comment]
@Ad1tyaS1ngh Seggs
