### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by redducc** [PixelOS-AOSP/official_devices#301]
## Name and Codename of the device you want to apply for 
```
sky
```

## Device Tree sources

```
https://github.com/sm4450-development/device_xiaomi_sky/tree/aosp
https://github.com/sm4450-development/vendor_xiaomi_sky/tree/aosp
https://github.com/sm4450-development/device_xiaomi_sky-kernel
```

## What ROM's do you maintain officially/unofficially
```
Paranoid Android (official)
```

## How long have you been building Custom ROMs
```
~3 years
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
redducc
```

### Link to your XDA thread of unofficial build

```
Link to where you have posted your build publically.
```

### Link to your unofficial PixelOS Build Post other than XDA

```
Link to where you have posted your build publically.
```

**Comment by kawaaii** [comment]
LGTM.
