### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Blaster4385** [PixelOS-AOSP/official_devices#318]
## Name and Codename of the device you want to apply for 
```
Pixel 7a (lynx)
```

## Device Tree sources

```
https://github.com/Blaster4385/device_google_gs201/tree/pos
https://github.com/Blaster4385/device_google_lynx
https://gitlab.com/Blaster4385/proprietary_vendor_google/-/tree/pos?ref_type=heads
```

## What ROM's do you maintain officially/unofficially
```
- Paranoid Android (Official)
- PixelBlaster-OS (Official/Owner)
```

## How long have you been building Custom ROMs
```
No Idea (Who tf remembers?)
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
https://github.com/Blaster4385/frameworks_base_pos/commit/4bad24b8a96683a42c20143a7f214b4cc83b60dc
```

### Telegram username
```
@V3NK4135H
```

### Link to your XDA thread of unofficial build

```

```

### Link to your unofficial PixelOS Build Post other than XDA

```

```

**Comment by kawaaii** [comment]
Telling "No Idea (Who tf remembers?)" shows how much patience and professional you are.
This kind of behaviour is strictly not accepted here.

You don't have posted any unofficial builds to verify whether the build is fully functional or not, nor have provided proper kernel source in the device tree sources.

Hence I am invalidating this issue right here.
