### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by inferno0230** [PixelOS-AOSP/official_devices#377]
## Name and Codename of the device you want to apply for 
```
OnePlus 12R (aston)
```

## Device Tree sources

```
https://github.com/OnePlus12R-development/android_device_oneplus_aston/tree/fourteen
https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/tree/fourteen
https://github.com/OnePlus12R-development/android_hardware_oplus/tree/fourteen
https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550
https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550-modules
https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550-devicetrees
```

## What ROM's do you maintain officially/unofficially
```
PixelOS(unofficial)
LineageOS(unofficial)
```

## How long have you been building Custom ROMs
```
3 Years
```

## Any Exceptions/special concern?
```
screen off gestures broken
```

## List of changes/patches applied to source, if any
```
https://github.com/OnePlus12R-development/PixelOs_vendor_aosp/commit/51744e407e617786516378d1529198c3fc44e12f

commits in https://github.com/OnePlus12R-development/android_hardware_oplus/commits/fourteen
```

### Telegram username
```
@inferno0230
```

### Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/12r-ace3-rom-14-unofficial-pixelos-aosp-24-05-24.4662225
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/OnePlus12RGlobalChat/36266
```

**Comment by cyberknight777** [comment]
I have some concerns about the kernel. 

1) Do fix authorship on https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/8254b2db98a88ccc214bd12dbe3abaca6ba7a6a0 

Ref: https://github.com/LineageOS/android_kernel_oneplus_sm8250/commit/ee237f992df6b137ffd480e5fa2b097daaa7559c

2) https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/b7c28a2cf9f9852c233b3120a2f2c68d190dc7c0 is redundant on modern devices as it does not 'improve' anything rather it would cause regressions. 

3) Why use https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/e86efc7bbf33eb231c2288e9503083d315dded9a at all? You do realize that this has severe repercussions for certain games made in unity as well as games like PUBG where it would ban the accounts with a reason of "hacking". No, even if the latter was fixed, it still causes issues with unity games and should not be utilized.

4) Have you actually disabled PROFILING after this https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/9885d2b54dffd5bc9116fcd92bbecae3e0974050 ?

5) Does this not break ABI? https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/f2fa33cb77f3f324e4a8ae6b35dfdd352215958c

6) I don't trust updated strings, they cause instability in very random situations. Would rather not have this merged IMO. https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/659867aa755866627cd201532ebb599611117b5c

7) Why are you using prebuilt dtb(o) https://github.com/OnePlus12R-development/android_device_oneplus_aston-kernel ? Don't you already have sources for DTS?

8) Isn't Full LTO the default in 5.10+ ? https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/commit/44a965b9da8ed348ad2ea11c4e66e3e9965c65f0

9) Why https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/blob/fourteen/BoardConfigCommon.mk#L134 ? Isn't it the default as per https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/f12b034afeb3a977bbb1c6584dedc0f3dc666f14 ?

10) Why set https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/blob/fourteen/BoardConfigCommon.mk#L135-142 explicitly?

11) 5.10+ kernels do full LLVM by default so explicitly setting that flag is unnecessary https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/commit/c21b46612705132da5706583cfa943a6e7bb1e93 

Ref: https://github.com/LineageOS/android_vendor_lineage/commit/41abb0b9708a4a929708b6073de0eefce79462ca

**Comment by inferno0230** [comment]
> I have some concerns about the kernel.
> 
>     1. Do fix authorship on [OnePlus12R-development/android_kernel_oneplus_sm8550@8254b2d](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/8254b2db98a88ccc214bd12dbe3abaca6ba7a6a0)
> 
Done

>     2. [OnePlus12R-development/android_kernel_oneplus_sm8550@b7c28a2](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/b7c28a2cf9f9852c233b3120a2f2c68d190dc7c0) is redundant on modern devices as it does not 'improve' anything rather it would cause regressions.
> 
>     3. Why use [OnePlus12R-development/android_kernel_oneplus_sm8550@e86efc7](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/e86efc7bbf33eb231c2288e9503083d315dded9a) at all? You do realize that this has severe repercussions for certain games made in unity as well as games like PUBG where it would ban the accounts with a reason of "hacking". No, even if the latter was fixed, it still causes issues with unity games and should not be utilized.
> 
>     4. Have you actually disabled PROFILING after this [OnePlus12R-development/android_kernel_oneplus_sm8550@9885d2b](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/9885d2b54dffd5bc9116fcd92bbecae3e0974050) ?
> 
>     5. Does this not break ABI? [OnePlus12R-development/android_kernel_oneplus_sm8550@f2fa33c](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/f2fa33cb77f3f324e4a8ae6b35dfdd352215958c)
> 
>     6. I don't trust updated strings, they cause instability in very random situations. Would rather not have this merged IMO. [OnePlus12R-development/android_kernel_oneplus_sm8550@659867a](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/659867aa755866627cd201532ebb599611117b5c)
> 
Removed 
>     8. Isn't Full LTO the default in 5.10+ ? [OnePlus12R-development/android_device_oneplus_sm8550-common@44a965b](https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/commit/44a965b9da8ed348ad2ea11c4e66e3e9965c65f0)
> 
>     9. Why https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/blob/fourteen/BoardConfigCommon.mk#L134 ? Isn't it the default as per [OnePlus12R-development/android_kernel_oneplus_sm8550@f12b034](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/f12b034afeb3a977bbb1c6584dedc0f3dc666f14) ?
> 
>     10. Why set https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/blob/fourteen/BoardConfigCommon.mk#L135-142 explicitly?
> 
>     11. 5.10+ kernels do full LLVM by default so explicitly setting that flag is unnecessary [OnePlus12R-development/android_device_oneplus_sm8550-common@c21b466](https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/commit/c21b46612705132da5706583cfa943a6e7bb1e93)
> 
Resolved

>     7. Why are you using prebuilt dtb(o) https://github.com/OnePlus12R-development/android_device_oneplus_aston-kernel ? Don't you already have sources for DTS?
Incomplete dts, front camera breaks
https://github.com/OnePlusOSS/android_kernel_oneplus_sm8550/issues/4#issuecomment-1964091233




I have also rebased device/kernel trees over LineageOS (i had to do this eventually to cleanup modules load list mess), 
please check device trees once again

**Comment by cyberknight777** [comment]
> > I have some concerns about the kernel.
> > ```
> > 1. Do fix authorship on [OnePlus12R-development/android_kernel_oneplus_sm8550@8254b2d](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/8254b2db98a88ccc214bd12dbe3abaca6ba7a6a0)
> > ```
> 
> Done
> 
> > ```
> > 2. [OnePlus12R-development/android_kernel_oneplus_sm8550@b7c28a2](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/b7c28a2cf9f9852c233b3120a2f2c68d190dc7c0) is redundant on modern devices as it does not 'improve' anything rather it would cause regressions.
> > 
> > 3. Why use [OnePlus12R-development/android_kernel_oneplus_sm8550@e86efc7](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/e86efc7bbf33eb231c2288e9503083d315dded9a) at all? You do realize that this has severe repercussions for certain games made in unity as well as games like PUBG where it would ban the accounts with a reason of "hacking". No, even if the latter was fixed, it still causes issues with unity games and should not be utilized.
> > 
> > 4. Have you actually disabled PROFILING after this [OnePlus12R-development/android_kernel_oneplus_sm8550@9885d2b](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/9885d2b54dffd5bc9116fcd92bbecae3e0974050) ?
> > 
> > 5. Does this not break ABI? [OnePlus12R-development/android_kernel_oneplus_sm8550@f2fa33c](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/f2fa33cb77f3f324e4a8ae6b35dfdd352215958c)
> > 
> > 6. I don't trust updated strings, they cause instability in very random situations. Would rather not have this merged IMO. [OnePlus12R-development/android_kernel_oneplus_sm8550@659867a](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/659867aa755866627cd201532ebb599611117b5c)
> > ```
> 
> Removed
> 
> > ```
> > 8. Isn't Full LTO the default in 5.10+ ? [OnePlus12R-development/android_device_oneplus_sm8550-common@44a965b](https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/commit/44a965b9da8ed348ad2ea11c4e66e3e9965c65f0)
> > 
> > 9. Why https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/blob/fourteen/BoardConfigCommon.mk#L134 ? Isn't it the default as per [OnePlus12R-development/android_kernel_oneplus_sm8550@f12b034](https://github.com/OnePlus12R-development/android_kernel_oneplus_sm8550/commit/f12b034afeb3a977bbb1c6584dedc0f3dc666f14) ?
> > 
> > 10. Why set https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/blob/fourteen/BoardConfigCommon.mk#L135-142 explicitly?
> > 
> > 11. 5.10+ kernels do full LLVM by default so explicitly setting that flag is unnecessary [OnePlus12R-development/android_device_oneplus_sm8550-common@c21b466](https://github.com/OnePlus12R-development/android_device_oneplus_sm8550-common/commit/c21b46612705132da5706583cfa943a6e7bb1e93)
> > ```
> 
> Resolved
> 
> > ```
> > 7. Why are you using prebuilt dtb(o) https://github.com/OnePlus12R-development/android_device_oneplus_aston-kernel ? Don't you already have sources for DTS?
> > ```
> 
> Incomplete dts, front camera breaks [OnePlusOSS/android_kernel_oneplus_sm8550#4 (comment)](https://github.com/OnePlusOSS/android_kernel_oneplus_sm8550/issues/4#issuecomment-1964091233)
> 
> I have also rebased device/kernel trees over LineageOS (i had to do this eventually to cleanup modules load list mess), please check device trees once again

Kernel looks okay however I would prefer you to fix OSS DTB(O) by reversing and diffing stock with yours.

**Comment by inferno0230** [comment]
> Kernel looks okay however I would prefer you to fix OSS DTB(O) by reversing and diffing stock with yours.

Okay, I'll see what i can do after I'm free from exams, till then I'll close this one

**Comment by inferno0230** [comment]
> fix OSS DTB(O)

Done

Also all repos have new pushes so might need to review again

**Comment by cyberknight777** [comment]
I would like you to rebase the kernel on top of LineageOS/android_kernel_oneplus_sm8550 so the commit history is neat. Otherwise kernel looks good. Ping me when it's done and I'll do a last check before marking kernel as accepted.

**Comment by inferno0230** [comment]
> I would like you to rebase the kernel on top of LineageOS/android_kernel_oneplus_sm8550 so the commit history is neat. Otherwise kernel looks good. Ping me when it's done and I'll do a last check before marking kernel as accepted.

Done

**Comment by cyberknight777** [comment]
lgtm.

**Comment by kawaaii** [comment]
https://github.com/OnePlus12R-development/android_device_oneplus_aston/commit/8ae64555485397962efc4146732e3f15b959a7d1
Unrequired

**Comment by kawaaii** [comment]
Rest changes LGTM.
