### ISSUE TITLE
Apply For Moto G9 (guamp)

### ISSUE THREAD

**Issue by DelightReza** [PixelOS-AOSP/official_devices#378]
## Name and Codename of the device you want to apply for 
```
Moto G9 (guamp)
```

## Device Tree sources
```
https://github.com/moto-guamp/android_device_motorola_guamp/tree/fourteen
https://github.com/moto-guamp/android_device_motorola_sm6225-common/tree/fourteen
https://github.com/LineageOS/android_kernel_motorola_sm6225
https://github.com/TheMuppets/proprietary_vendor_motorola_sm6225-common
https://github.com/TheMuppets/proprietary_vendor_motorola_guamp
```

## What ROM's do you maintain officially/unofficially
```
LineageOS (official)
InfinityX (official)
```

## How long have you been building Custom ROMs
```
4 year 👀
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
DelightReza
```

### Link to your XDA thread of unofficial build

```
NA
```

### Link to your unofficial PixelOS Build Post other than XDA
```
https://t.me/RazaDroidProject/86
```

**Comment by kawaaii** [comment]
Is there any reason why you haven't linked your XDA thread?

**Comment by DelightReza** [comment]
> Is there any reason why you haven't linked your XDA thread?

Mostly brazilian users so use telegram more

**Comment by whyredfire** [comment]
> > Is there any reason why you haven't linked your XDA thread?
> 
> Mostly brazilian users so use telegram more

XDA thread is a requirement. It takes about 10 minutes at most to create one and doesn't need to be updated regularly.
Here's a link to our template https://github.com/PixelOS-AOSP/official_devices/blob/fourteen/docs/XDA_template.txt.

**Comment by DelightReza** [comment]
> > > Is there any reason why you haven't linked your XDA thread?
> > 
> > 
> > Mostly brazilian users so use telegram more
> 
> XDA thread is a requirement. It takes about 10 minutes at most to create one and doesn't need to be updated regularly. Here's a link to our template https://github.com/PixelOS-AOSP/official_devices/blob/fourteen/docs/XDA_template.txt.

https://xdaforums.com/t/rom-14-unofficial-pixelos-aosp-stable.4673807/

Done

**Comment by cyberknight777** [comment]
Kernel looks good with one exception: https://github.com/LineageOS/android_kernel_motorola_sm6225/commit/3e33b60fe64b81800473723fed3ed851a02892fa. This change used to break OTG on several devices back in the day, does OTG work fine on your device with it?

**Comment by DelightReza** [comment]
> Kernel looks good with one exception: [LineageOS/android_kernel_motorola_sm6225@3e33b60](https://github.com/LineageOS/android_kernel_motorola_sm6225/commit/3e33b60fe64b81800473723fed3ed851a02892fa). This change used to break OTG on several devices back in the day, does OTG work fine on your device with it?

OTG works fine
