### ISSUE TITLE
New maintainer for Redmi note 13 Pro 5G

### ISSUE THREAD

**Issue by JYRRC** [PixelOS-AOSP/official_devices#384]
## Name and Codename of the device you want to apply for 
```
Redmi Note 13 Pro 5G (garnet)
```

## Device Tree sources

```
https://github.com/hub-marble/device_xiaomi_garnet
https://github.com/hub-marble/device_xiaomi_garnet-kernel
https://github.com/hub-marble/vendor_xiaomi_garnet
```

## What ROM's do you maintain officially/unofficially
```
Crdroid / droidx-UI / cherishOS
```

## How long have you been building Custom ROMs
```
About 4 years
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@JYR_RC
```

### Link to your XDA thread of unofficial build

```
The build is completely stable but I haven't posted it.
```

### Link to your unofficial PixelOS Build Post other than XDA

```
The build is completely stable but I haven't posted it.
```

**Comment by kawaaii** [comment]
You violate following rules mentioned in our Maintainer requirements:

1.3. You MUST have experience maintaining the ROM on an unofficial basis for some amount of time. you MUST NOT instantly make a build and apply, that'll mean an instant rejection.
1.6. MUST NOT include any stolen or "kanged" commits without crediting the original author.
1.9. You SHOULD have made significant contributions to the device sources.

**Comment by JYRRC** [comment]
I don't agree but I accept it
