### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by vladislavmaiocchi** [PixelOS-AOSP/official_devices#386]
## Name and Codename of the device you want to apply for 
Redmi Note 13 pro 5G (Garnet)
Your device name (Your device codename)
Redmi note 13 pro 5G (Garnet)

## Device Tree sources

```
https://github.com/garnet-stuff/device_xiaomi_garnet
https://github.com/garnet-stuff/device_xiaomi_garnet-kernel
https://github.com/garnet-stuff/vendor_xiaomi_garnet
```

## What ROM's do you maintain officially/unofficially
```
Insert here
Pixel os

## How long have you been building Custom ROMs
``` 
Insert here
2 years

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
DarckWizard
Your Telegram username
DarckWizard

### Link to your XDA thread of unofficial build

```
Link to where you have posted your build publically.

https://drive.google.com/file/d/1pampcsad4Bb6-uMI30LtA5P0hgXUxVaj/view


### Link to your unofficial PixelOS Build Post other than XDA
https://t.me/pixelgarnet
Refer Maintainer Requirements -->
```
Link to where you have posted your build publically.
```
https://t.me/pixelgarnet

**Comment by cyberknight777** [comment]
This tree was already rejected so rejecting now.
