### ISSUE TITLE
New maintainer for a52q

### ISSUE THREAD

**Issue by koko-07870** [PixelOS-AOSP/official_devices#398]
## Name and Codename of the device you want to apply for 
```
Galaxy A52 (a52q)
```

## Device Tree sources

```
https://github.com/koko-07870/android_device_samsung_a52q
https://github.com/koko-07870/android_device_samsung_sm7125-common
https://github.com/TheMuppets/proprietary_vendor_samsung_a52q
https://github.com/TheMuppets/proprietary_vendor_samsung_sm7125-common
https://github.com/koko-07870/android_kernel_samsung_sm7125
https://github.com/koko-07870/android_hardware_samsung
```

## What ROM's do you maintain officially/unofficially
```
None for now except PixelOS. Was maintaining derpfest unofficially before pixelos.
```

## How long have you been building Custom ROMs
```
2 months
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
None
```

### Telegram username
```
@kok_o3
```

### Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-unofficial-stable-pixelos-for-galaxy-a52-4g.4681912/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/a525xx/102136
```

**Comment by whyredfire** [comment]
Hi, please revisit the maintainer requirements.

To begin with, other than patience, Rule 1.2 of maintainer requirements is violated.
