### ISSUE TITLE
Xiaomi 12 Pro download not available

### ISSUE THREAD

**Issue by Dadas196** [PixelOS-AOSP/official_devices#403]
The page for the Xiaomi 12 pro doesn't load when I open it. The problem is probably that when the device was recalculated from (dagda to zeus), the link source code was forgotten to change the name from dagda to zeus in order to get to the Sourceforge page. This means that it is not possible to go directly from the page with the download button to the Source Forge page.

**Comment by whyredfire** [comment]
Hi, it will be fixed with the initial release of dada.
For now, you can use https://sourceforge.net/projects/pixelos-releases/files/fourteen/zeus/ to download the older builds.
