### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by anoosragh69** [PixelOS-AOSP/official_devices#408]
## Name and Codename of the device you want to apply for 
```
Motorola G60/G40 Fusion (hanoip)
```

## Device Tree sources

```
https://github.com/anoosragh69/android_device_motorola_hanoip/
https://github.com/anoosragh69/kernel_motorola_hanoip
https://github.com/anoosragh69/android_vendor_motorola_hanoip
```

## What ROM's do you maintain officially/unofficially
```
PixelOS (Unofficial)
ProjectSakura (Official)
```

## How long have you been building Custom ROMs
```
3-4 years
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
anoosragh69
```

### Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-unofficial-pixelos-aosp-stable-g40f-g60.4657000/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/anoosupdates/1143
```

**Comment by kawaaii** [comment]
1. This is not a QPR change.
https://github.com/anoosragh69/android_device_motorola_hanoip/commit/f85e8a1349c496c5865906a370d8bd35599c4237

2. Why are you disabling DT2W?
https://github.com/anoosragh69/android_device_motorola_hanoip/commit/d0203178a8733572d3db1a6c284ddf681e35bf5e

3. Already done by default if you're explicitly disabling LLVM binutils.
https://github.com/anoosragh69/android_device_motorola_hanoip/commit/8ab0919f76d249efbdded235fadadb31e6ab86b4

4. The config you're changing doesn't even exist.
https://github.com/anoosragh69/android_device_motorola_hanoip/commit/18bb5a3f0a10a491c6d36d07db6a2aae086c6595

5. Why?
https://github.com/anoosragh69/android_device_motorola_hanoip/commit/9d89021bcff9a14395150ea4a9e4ff99cc27ba61

6. Why? Address only necessary denials. Why would kernel require require to search in /mnt/vendor/ directory.
https://github.com/anoosragh69/android_device_motorola_hanoip/commit/4d4cab44bb49a66bccc2919a7a52b6f48dcd6706

7. Commit message and the changes you did are not really matching.
https://github.com/anoosragh69/android_device_motorola_hanoip/commit/582f4923f2214dc431391cd29c3c33ac7e48495a#diff-fccec6302c27471369e967c30307e1374a6d019598b4bcc92095b839dce479c5

8. Not good way to commit a squash revert.
https://github.com/anoosragh69/android_device_motorola_hanoip/commit/a1f64274f08205419f722bd9f7a4a33c18c1f118

Looking at the changes you did overall in the tree, I don't think you're fit enough to join PixelOS maintainer team. Please apply again after gaining more experience.

**Comment by anoosragh69** [comment]
1. was a typo
2. one tap to wake with moto gestures is there, so dt2s is useless.
3. was reverted
4, 5 and 6 are mistakes by me.
seems like i have a lot to improve, thnkz for checking my application.
