### ISSUE TITLE
Wrong image URLs in Banner Archive

### ISSUE THREAD

**Issue by pdimu** [PixelOS-AOSP/official_devices#413]
i recently opened the [banner archive](https://blog.pixelos.net/docs/resources/BannersArchive) to see what are they like, but the links to the images were broken, so i pulled inspect up and got the github links to the images, which returned a 404

the latest banner image on the site: https://github.com/PixelOS-AOSP/official_devices/raw/thirteen/banners/latest.png
the latest banner image on the repo: https://github.com/PixelOS-AOSP/official_devices/raw/fourteen/banners/latest.png

> [!NOTE]
> i didn't know where to file the issue, because there isn't a repo for the website, so excuse me if i've filed in the wrong place

**Comment by pdimu** [comment]
i forgot to mention that all the images have broken links

**Comment by kawaaii** [comment]
Fixed!
