### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by onesmiledx** [PixelOS-AOSP/official_devices#414]
## Name and Codename of the device you want to apply for 
```
Samsung Galaxy A71 4G
```

## Device Tree sources

```
https://github.com/onesmiledx/android_device_samsung_a71
https://github.com/onesmiledx/android_device_samsung_a71-common
https://github.com/onesmiledx/android_kernel_samsung_a71
https://github.com/TheMuppets/proprietary_vendor_samsung_a71
https://github.com/TheMuppets/proprietary_vendor_samsung_a71-common
https://github.com/onesmiledx/android_hardware_samsung (this need to fix bootloop, without that rom is not booting)
```

## What ROM's do you maintain officially/unofficially
```
RisingOS (unofficially)
PixelOS (Unofficially)
```

## How long have you been building Custom ROMs
```
4 months
```

## Any Exceptions/special concern?
```
VoLTE
```

## List of changes/patches applied to source, if any
```
LineageOS device tree convert to AOSP
```

### Telegram username
```
@whystarlix
```

### Link to your XDA thread of unofficial build

```
https://xdaforums.com/t/rom-14-0-unofficial-stable-20240904-pixelos-14-qpr3-for-samsung-galaxy-a71-4g-ss-ds.4690578/#post-89695414
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/starlixx/243
```

**Comment by kawaaii** [comment]
We don't see any significant contributions you made to the tree from which we can determine that you are actively involved and committed to the development. Try again next time after you've made some significant contributions.
