### ISSUE TITLE
New maintainer Redmi note 13 pro 5g (garnet)

### ISSUE THREAD

**Issue by vladislavmaiocchi** [PixelOS-AOSP/official_devices#428]
## Name and Codename of the device you want to apply for 
Redmi note 13 pro 5g (garnet)

## Device Tree sources

```
https://github.com/aosp-garnet/android_device_xiaomi_garnet
https://github.com/aosp-garnet/android_device_xiaomi_garnet-kernel
https://github.com/aosp-garnet/android_vendor_xiaomi_garnet
```

## What ROM's do you maintain officially/unofficially
PixelOS

## How long have you been building Custom ROMs
3 years 

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
@DarckWizard

### Link to your XDA thread of unofficial build

```
Link to where you have posted your build publically.
https://t.me/Garnetbd

### Link to your unofficial PixelOS Build Post other than XDA
https://t.me/pixelgarnet and build link Is (https://drive.google.com/file/d/1-3X_eQwwG39GAJKtI6-GWH9Z-48hTOH3/view?usp=drivesdk)

```
Link to where you have posted your build publically.
```
https://t.me/pixelgarnet

**Comment by vladislavmaiocchi** [comment]
For tree i asked permission to unmoved21

**Comment by kawaaii** [comment]
Read https://blog.pixelos.net/docs/JoinTheTeam/MaintainersRequirements and apply again.
