### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by kibria5** [PixelOS-AOSP/official_devices#429]
```
Redmi Note 13 Pro 5G/Poco X6 5G (garnet)
```

## Device Tree sources
```
https://github.com/kibria5/android_device_xiaomi_garnet.git
https://github.com/kibria5/android_device_xiaomi_garnet-kernel.git
https://github.com/kibria5/android_vendor_xiaomi_garnet.git
```

## What ROM's do you maintain officially/unofficially
```
PixelStar Official
```

## How long have you been building Custom ROMs
```
3 year+
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@kibria5
```

### Link to your XDA thread of unofficial build
```
https://xdaforums.com/t/rom-14-unofficial-pixelos-aosp-stable-garnet.4706259/
```

### Link to your unofficial PixelOS Build Post other than XDA
```
https://t.me/garnet_updates/649
https://t.me/GarnetAOSP/3900
```

**Comment by kawaaii** [comment]
Apply again after PixelOS 15 Stable Release.

**Comment by kibria5** [comment]
> Apply again after PixelOS 15 Stable Release.

Thank you for the update. I'll make sure to follow up after the PixelOS 15 Stable Release.

**Comment by bl4ze1g** [comment]
any update on this? i would love to have an official build for my phone
